param (
    [string]$ProjectName = ""
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
Add-Type -AssemblyName System.IO.Compression.FileSystem

function Get-FileTextContent($filePath) {
    if ($filePath.EndsWith(".docx", [System.StringComparison]::OrdinalIgnoreCase)) {
        try {
            $zip = [System.IO.Compression.ZipFile]::OpenRead($filePath)
            $entry = $zip.GetEntry("word/document.xml")
            if ($entry) {
                $stream = $entry.Open()
                $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
                $xmlContent = $reader.ReadToEnd()
                $reader.Close()
                $stream.Close()
                $zip.Dispose()
                
                $xml = [xml]$xmlContent
                $ns = New-Object System.Xml.XmlNamespaceManager($xml.NameTable)
                $ns.AddNamespace("w", "http://schemas.openxmlformats.org/wordprocessingml/2006/main")
                
                $paras = $xml.SelectNodes("//w:p", $ns)
                $lines = [System.Collections.Generic.List[string]]::new()
                foreach ($p in $paras) {
                    $tNodes = $p.SelectNodes(".//w:t", $ns)
                    $pText = ($tNodes | ForEach-Object { $_.InnerText }) -join ""
                    if ($pText -and $pText.Trim().Length -gt 0) {
                        $lines.Add($pText.Trim())
                    }
                }
                return ($lines -join "`r`n")
            }
            $zip.Dispose()
        } catch {
            Write-Warning "Loi doc file docx: $filePath ($($_))"
        }
        return ""
    } else {
        return [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)
    }
}

$toolsDir = if ($PSScriptRoot) { $PSScriptRoot } else { "d:\Novel\tools" }
$rootDir = (Get-Item $toolsDir).Parent.FullName

$excludeDirs = @("tools", ".git", ".gemini", ".obsidian", "audio", "scratch", "dist", "node_modules")
$projectsDir = Join-Path $rootDir "projects"
$allNovelDirs = @()
if (Test-Path $projectsDir) {
    $allNovelDirs += Get-ChildItem -Path $projectsDir -Directory | Where-Object { $excludeDirs -notcontains $_.Name -and $_.Name -ne "projects" -and $_.Name -ne "web" }
}
$allNovelDirs += Get-ChildItem -Path $rootDir -Directory | Where-Object { $excludeDirs -notcontains $_.Name -and $_.Name -ne "projects" -and $_.Name -ne "web" }
$novelDirs = $allNovelDirs | Sort-Object FullName -Unique

if ($novelDirs.Count -eq 0) {
    Write-Host "Khong tim thay thu muc du an truyen nao trong $rootDir" -ForegroundColor Yellow
    exit 0
}

$activeDir = $novelDirs | Where-Object { $_.Name -eq $ProjectName } | Select-Object -First 1
if (-not $activeDir) {
    $activeDir = $novelDirs | Where-Object { $_.Name -eq "Chu_Thuat_Su_Dung_Gia" } | Select-Object -First 1
    if (-not $activeDir) { $activeDir = $novelDirs[0] }
}

$webDir = Join-Path $rootDir "web"
if (-not (Test-Path $webDir)) { New-Item -ItemType Directory -Path $webDir -Force | Out-Null }
$outputFile = Join-Path $webDir "chapters.js"
$sb = [System.Text.StringBuilder]::new()
$q = [char]34
$bt = [char]96

[void]$sb.AppendLine("// Auto-generated by build_chapters_js.ps1 - Multi-Novel Database")
[void]$sb.AppendLine("window.ALL_NOVELS = {")

$novelCount = 0

foreach ($nDir in $novelDirs) {
    $nName = $nDir.Name
    $transDir = Join-Path $nDir.FullName "translated"
    $galleryPath = Join-Path $nDir.FullName "gallery.json"
    
    $nTitle = $nName.Replace("_", " ")
    $nOrigTitle = "Light Novel Reader"
    
    if ($nName -eq "Chu_Thuat_Su_Dung_Gia") {
        $nTitle = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("Q2jDuiB0aHXhuq10IHPGsCBraMO0bmcgdGjhu4MgdHLhu58gdGjDoG5oIETFqW5nIEdp4bqj"))
        $nOrigTitle = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("5Ziq6KGT5bir44Gv5YuH6ICF44Gr44Gq44KM44Gq44GEIC0gSnVqdXRzdXNoaSB3YSBZdXVzaGEgbmkgTmFyZW5haQ=="))
    }

    $chapters = [System.Collections.Generic.List[PSCustomObject]]::new()
    if (Test-Path $transDir) {
        $allFiles = Get-ChildItem -Path $transDir | Where-Object {
            $_.Name -match '\.(md|docx|txt)$' -and 
            -not $_.Name.Equals('README.md', [System.StringComparison]::OrdinalIgnoreCase) -and 
            -not $_.Name.StartsWith('~$')
        }
        
        $fileMap = @{}
        foreach ($f in $allFiles) {
            $baseKey = $f.BaseName
            if (-not $fileMap.ContainsKey($baseKey) -or $f.Extension -eq '.md') {
                $fileMap[$baseKey] = $f
            }
        }

        foreach ($f in $fileMap.Values) {
            $rawContent = Get-FileTextContent $f.FullName
            if ([string]::IsNullOrWhiteSpace($rawContent)) { continue }

            $num = 0
            if ($f.Name -match '^chuong_(\d+)') {
                $num = [int]$matches[1]
            }

            $id = "chuong_$num"
            $title = "Tap $num"
            if ($rawContent -match '(?m)^#\s+(.*?)(?:\r?\n|$)') {
                $title = $matches[1].Trim()
            }

            $volume = "Tap 1"
            if ($rawContent -match '(?:\*\*Thuoc:\*\*|Thuoc:|\*\*Thuộc:\*\*|Thuộc:)\s*(.*?)(?:\r?\n|$)') {
                $volume = $matches[1].Trim()
            }

            $storyBody = ""
            $parts = $rawContent -split '(?m)^---\s*$', 2
            if ($parts.Length -gt 1) {
                $storyBody = $parts[1].Trim()
            } else {
                $lines = $rawContent -split '\r?\n'
                if ($lines.Length -gt 1 -and ($lines[0].Trim() -eq $title -or $lines[0].StartsWith('#'))) {
                    $storyBody = ($lines[1..($lines.Length - 1)] -join "`r`n").Trim()
                } else {
                    $storyBody = $rawContent.Trim()
                }
            }

            $escapedBody = $storyBody.Replace('\', '\\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')

            $chObj = [PSCustomObject]@{
                id = $id
                number = $num
                title = $title
                volume = $volume
                path = "../$nName/translated/$($f.Name)"
                content = $escapedBody
            }
            $chapters.Add($chObj)
        }

        $chapters.Sort({
            param($a, $b)
            if ($a.number -ne $b.number) { return $a.number.CompareTo($b.number) }
            return $a.title.CompareTo($b.title)
        })
    }

    $galleryJson = "[]"
    if (Test-Path $galleryPath) {
        try {
            $galleryJson = [System.IO.File]::ReadAllText($galleryPath, [System.Text.Encoding]::UTF8).Trim()
            if ([string]::IsNullOrWhiteSpace($galleryJson)) { $galleryJson = "[]" }
        } catch {
            $galleryJson = "[]"
        }
    }

    $escNName = $nName.Replace('\', '\\').Replace('"', '\"')
    $escNTitle = $nTitle.Replace('\', '\\').Replace('"', '\"')
    $escNOrigTitle = $nOrigTitle.Replace('\', '\\').Replace('"', '\"')

    [void]$sb.AppendLine("    " + $q + $escNName + $q + ": {")
    [void]$sb.AppendLine("        " + $q + "id" + $q + ": " + $q + $escNName + $q + ",")
    [void]$sb.AppendLine("        " + $q + "title" + $q + ": " + $q + $escNTitle + $q + ",")
    [void]$sb.AppendLine("        " + $q + "originalTitle" + $q + ": " + $q + $escNOrigTitle + $q + ",")
    [void]$sb.AppendLine("        " + $q + "chapters" + $q + ": [")

    for ($i = 0; $i -lt $chapters.Count; $i++) {
        $c = $chapters[$i]
        $escId = $c.id.Replace('\', '\\').Replace('"', '\"')
        $escTitle = $c.title.Replace('\', '\\').Replace('"', '\"')
        $escVolume = $c.volume.Replace('\', '\\').Replace('"', '\"')
        $escPath = $c.path.Replace('\', '\\').Replace('"', '\"')

        [void]$sb.AppendLine("            {")
        [void]$sb.AppendLine("                " + $q + "id" + $q + ": " + $q + $escId + $q + ",")
        [void]$sb.AppendLine("                " + $q + "number" + $q + ": " + $c.number + ",")
        [void]$sb.AppendLine("                " + $q + "title" + $q + ": " + $q + $escTitle + $q + ",")
        [void]$sb.AppendLine("                " + $q + "volume" + $q + ": " + $q + $escVolume + $q + ",")
        [void]$sb.AppendLine("                " + $q + "path" + $q + ": " + $q + $escPath + $q + ",")
        [void]$sb.AppendLine("                " + $q + "content" + $q + ": " + $bt + $c.content + $bt)
        if ($i -lt ($chapters.Count - 1)) {
            [void]$sb.AppendLine("            },")
        } else {
            [void]$sb.AppendLine("            }")
        }
    }

    $glossaryTerms = ""
    $glossaryChars = ""
    $glossaryEvents = ""
    $styleGuide = ""

    $termsPath = Join-Path $nDir.FullName "glossary\terms.md"
    $charsPath = Join-Path $nDir.FullName "glossary\characters.md"
    $eventsPath = Join-Path $nDir.FullName "glossary\events.md"
    $stylePath = Join-Path $nDir.FullName "style_guide.md"

    if (Test-Path $termsPath) {
        $glossaryTerms = [System.IO.File]::ReadAllText($termsPath, [System.Text.Encoding]::UTF8)
        $glossaryTerms = $glossaryTerms.Replace('\', '\\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $charsPath) {
        $glossaryChars = [System.IO.File]::ReadAllText($charsPath, [System.Text.Encoding]::UTF8)
        $glossaryChars = $glossaryChars.Replace('\', '\\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $eventsPath) {
        $glossaryEvents = [System.IO.File]::ReadAllText($eventsPath, [System.Text.Encoding]::UTF8)
        $glossaryEvents = $glossaryEvents.Replace('\', '\\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $stylePath) {
        $styleGuide = [System.IO.File]::ReadAllText($stylePath, [System.Text.Encoding]::UTF8)
        $styleGuide = $styleGuide.Replace('\', '\\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }

    [void]$sb.AppendLine("        ],")
    [void]$sb.AppendLine("        " + $q + "gallery" + $q + ": " + $galleryJson + ",")
    [void]$sb.AppendLine("        " + $q + "glossary" + $q + ": {")
    [void]$sb.AppendLine("            " + $q + "terms" + $q + ": " + $bt + $glossaryTerms + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "characters" + $q + ": " + $bt + $glossaryChars + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "events" + $q + ": " + $bt + $glossaryEvents + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "style_guide" + $q + ": " + $bt + $styleGuide + $bt)
    [void]$sb.AppendLine("        }")
    
    $novelCount++
    if ($novelCount -lt $novelDirs.Count) {
        [void]$sb.AppendLine("    },")
    } else {
        [void]$sb.AppendLine("    }")
    }
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("window.ACTIVE_NOVEL_KEY = " + $q + $activeDir.Name + $q + ";")
[void]$sb.AppendLine("window.NOVEL_DATA = window.ALL_NOVELS[window.ACTIVE_NOVEL_KEY] || Object.values(window.ALL_NOVELS)[0];")
[void]$sb.AppendLine("")

$cfgPath = Join-Path $toolsDir "config.json"
$sanitizedCfgJson = "{}"
if (Test-Path $cfgPath) {
    try {
        $cfgObj = Get-Content $cfgPath -Raw -Encoding UTF8 | ConvertFrom-Json
        # Xóa bỏ hoàn toàn API key nhạy cảm để bảo mật tuyệt đối khi push GitHub
        if ($cfgObj.PSObject.Properties['gemini_api_key']) { $cfgObj.gemini_api_key = "" }
        if ($cfgObj.PSObject.Properties['relay_api_key']) { $cfgObj.relay_api_key = "" }
        if ($cfgObj.PSObject.Properties['api_key']) { $cfgObj.api_key = "" }
        $sanitizedCfgJson = ($cfgObj | ConvertTo-Json -Compress)
    } catch {
        $sanitizedCfgJson = "{}"
    }
}
[void]$sb.AppendLine("window.APP_CONFIG = " + $sanitizedCfgJson + ";")

$rootChaptersPath = Join-Path $rootDir "chapters.js"
$rootIndexPath = Join-Path $rootDir "index.html"
[System.IO.File]::WriteAllText($outputFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
[System.IO.File]::WriteAllText($rootChaptersPath, $sb.ToString(), [System.Text.Encoding]::UTF8)

$docTruyenPath = Join-Path $webDir "Doc_Truyen.html"
$indexPath = Join-Path $webDir "index.html"
if (Test-Path $docTruyenPath) {
    $htmlContent = [System.IO.File]::ReadAllText($docTruyenPath, [System.Text.Encoding]::UTF8)
    $htmlContent = $htmlContent -replace 'src="chapters\.js(?:\?v=[^"]+)?"', 'src="chapters.js"'
    [System.IO.File]::WriteAllText($indexPath, $htmlContent, [System.Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($docTruyenPath, $htmlContent, [System.Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($rootIndexPath, $htmlContent, [System.Text.Encoding]::UTF8)
}

Write-Host "Da dong bo thanh cong $($novelDirs.Count) bo truyen vao $outputFile va index.html (Active: $($activeDir.Name))." -ForegroundColor Green
