param (
    [string]$ProjectName = ""
)

[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
[Console]::InputEncoding = [System.Text.Encoding]::UTF8
Add-Type -AssemblyName System.IO.Compression.FileSystem

function Get-FileTextContent($filePath) {
    if ($filePath.EndsWith(".docx", [System.StringComparison]::OrdinalIgnoreCase)) {
        try {
            $zip = [System.IO.Compression.ZipFile]::OpenRead($filePath)
            $entry = $zip.GetEntry("word/document.xml")
            if ($entry) {
                $stream = $entry.Open()
                $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
                $xmlContent = $reader.ReadToEnd()
                $reader.Close()
                $stream.Close()
                $zip.Dispose()
                
                $xml = [xml]$xmlContent
                $ns = New-Object System.Xml.XmlNamespaceManager($xml.NameTable)
                $ns.AddNamespace("w", "http://schemas.openxmlformats.org/wordprocessingml/2006/main")
                
                $paras = $xml.SelectNodes("//w:p", $ns)
                $lines = [System.Collections.Generic.List[string]]::new()
                foreach ($p in $paras) {
                    $tNodes = $p.SelectNodes(".//w:t", $ns)
                    $pText = ($tNodes | ForEach-Object { $_.InnerText }) -join ""
                    if ($pText -and $pText.Trim().Length -gt 0) {
                        $lines.Add($pText.Trim())
                    }
                }
                return ($lines -join "`r`n")
            }
            $zip.Dispose()
        } catch {
            Write-Warning "Loi doc file docx: $filePath ($($_))"
        }
        return ""
    } else {
        return [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)
    }
}

$toolsDir = if ($PSScriptRoot) { $PSScriptRoot } else { "d:\Novel\tools" }
$rootDir = (Get-Item $toolsDir).Parent.FullName

$excludeDirs = @("tools", ".git", ".gemini", ".obsidian", "audio", "scratch", "dist", "node_modules")
$projectsDir = Join-Path $rootDir "projects"
$allNovelDirs = @()
if (Test-Path $projectsDir) {
    $allNovelDirs += Get-ChildItem -Path $projectsDir -Directory | Where-Object { $excludeDirs -notcontains $_.Name -and $_.Name -ne "projects" -and $_.Name -ne "web" }
}
$allNovelDirs += Get-ChildItem -Path $rootDir -Directory | Where-Object { $excludeDirs -notcontains $_.Name -and $_.Name -ne "projects" -and $_.Name -ne "web" }
$novelDirs = $allNovelDirs | Sort-Object FullName -Unique

if ($novelDirs.Count -eq 0) {
    Write-Host "Khong tim thay thu muc du an truyen nao trong $rootDir" -ForegroundColor Yellow
    exit 0
}

$activeDir = $novelDirs | Where-Object { $_.Name -eq $ProjectName } | Select-Object -First 1
if (-not $activeDir) {
    $activeDir = $novelDirs | Where-Object { $_.Name -eq "Chu_Thuat_Su_Dung_Gia" } | Select-Object -First 1
    if (-not $activeDir) { $activeDir = $novelDirs[0] }
}

$webDir = Join-Path $rootDir "web"
if (-not (Test-Path $webDir)) { New-Item -ItemType Directory -Path $webDir -Force | Out-Null }
$outputFile = Join-Path $webDir "chapters.js"
$sb = [System.Text.StringBuilder]::new()
$q = [char]34
$bt = [char]96

[void]$sb.AppendLine("// Auto-generated by build_chapters_js.ps1 - Multi-Novel Database")
[void]$sb.AppendLine("window.ALL_NOVELS = {")

$novelCount = 0
foreach ($dir in $novelDirs) {
    $nKey = $dir.Name
    $nTitle = $dir.Name.Replace("_", " ")
    $metaFile = Join-Path $dir.FullName "meta.json"
    if (Test-Path $metaFile) {
        try {
            $meta = Get-Content $metaFile -Raw -Encoding UTF8 | ConvertFrom-Json
            if ($meta.title) { $nTitle = $meta.title }
        } catch {}
    }

    [void]$sb.AppendLine("    " + $q + $nKey + $q + ": {")
    [void]$sb.AppendLine("        " + $q + "title" + $q + ": " + $q + $nTitle.Replace($q, "" + $q) + $q + ",")
    [void]$sb.AppendLine("        " + $q + "chapters" + $q + ": [")

    $transDir = Join-Path $dir.FullName "translated"
    if (Test-Path $transDir) {
        $files = Get-ChildItem -Path $transDir -File | Where-Object { $_.Extension -match "\.(md|txt|docx)$" -and $_.Name -ne "README.md" }
        $sortedFiles = $files | Sort-Object {
            if ($_.BaseName -match "(\d+)") { [int]$Matches[1] } else { 0 }
        }

        $cCount = 0
        foreach ($file in $sortedFiles) {
            $title = $file.BaseName
            $ep = 0
            if ($title -match "(\d+)") {
                $ep = [int]$Matches[1]
            }

            $content = Get-FileTextContent $file.FullName
            $content = $content.Replace('', '\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')

            [void]$sb.AppendLine("            {")
            [void]$sb.AppendLine("                " + $q + "ep" + $q + ": " + $ep + ",")
            [void]$sb.AppendLine("                " + $q + "title" + $q + ": " + $q + $title.Replace($q, "" + $q) + $q + ",")
            [void]$sb.AppendLine("                " + $q + "content" + $q + ": " + $bt + $content + $bt)
            
            $cCount++
            if ($cCount -lt $sortedFiles.Count) {
                [void]$sb.AppendLine("            },")
            } else {
                [void]$sb.AppendLine("            }")
            }
        }
    }

    $galleryJson = "[]"
    $galleryFile = Join-Path $dir.FullName "gallery.json"
    if (Test-Path $galleryFile) {
        try {
            $galleryJson = Get-Content $galleryFile -Raw -Encoding UTF8
            if (-not $galleryJson.Trim()) { $galleryJson = "[]" }
        } catch {
            $galleryJson = "[]"
        }
    }

    $glossaryDir = Join-Path $dir.FullName "glossary"
    $termsPath = Join-Path $glossaryDir "terms.md"
    $charsPath = Join-Path $glossaryDir "characters.md"
    $eventsPath = Join-Path $glossaryDir "events.md"
    $stylePath = Join-Path $dir.FullName "style_guide.md"

    $glossaryTerms = ""
    $glossaryChars = ""
    $glossaryEvents = ""
    $styleGuide = ""

    if (Test-Path $termsPath) {
        $glossaryTerms = [System.IO.File]::ReadAllText($termsPath, [System.Text.Encoding]::UTF8)
        $glossaryTerms = $glossaryTerms.Replace('', '\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $charsPath) {
        $glossaryChars = [System.IO.File]::ReadAllText($charsPath, [System.Text.Encoding]::UTF8)
        $glossaryChars = $glossaryChars.Replace('', '\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $eventsPath) {
        $glossaryEvents = [System.IO.File]::ReadAllText($eventsPath, [System.Text.Encoding]::UTF8)
        $glossaryEvents = $glossaryEvents.Replace('', '\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }
    if (Test-Path $stylePath) {
        $styleGuide = [System.IO.File]::ReadAllText($stylePath, [System.Text.Encoding]::UTF8)
        $styleGuide = $styleGuide.Replace('', '\').Replace("$([char]96)", "\$([char]96)").Replace('${', '\${')
    }

    [void]$sb.AppendLine("        ],")
    [void]$sb.AppendLine("        " + $q + "gallery" + $q + ": " + $galleryJson + ",")
    [void]$sb.AppendLine("        " + $q + "glossary" + $q + ": {")
    [void]$sb.AppendLine("            " + $q + "terms" + $q + ": " + $bt + $glossaryTerms + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "characters" + $q + ": " + $bt + $glossaryChars + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "events" + $q + ": " + $bt + $glossaryEvents + $bt + ",")
    [void]$sb.AppendLine("            " + $q + "style_guide" + $q + ": " + $bt + $styleGuide + $bt)
    [void]$sb.AppendLine("        }")
    
    $novelCount++
    if ($novelCount -lt $novelDirs.Count) {
        [void]$sb.AppendLine("    },")
    } else {
        [void]$sb.AppendLine("    }")
    }
}

[void]$sb.AppendLine("};")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("window.ACTIVE_NOVEL_KEY = " + $q + $activeDir.Name + $q + ";")
[void]$sb.AppendLine("window.NOVEL_DATA = window.ALL_NOVELS[window.ACTIVE_NOVEL_KEY] || Object.values(window.ALL_NOVELS)[0];")
[void]$sb.AppendLine("")

$cfgPath = Join-Path $toolsDir "config.json"
$sanitizedCfgJson = "{}"
if (Test-Path $cfgPath) {
    try {
        $cfgObj = Get-Content $cfgPath -Raw -Encoding UTF8 | ConvertFrom-Json
        if ($cfgObj.PSObject.Properties['gemini_api_key']) { $cfgObj.gemini_api_key = "" }
        if ($cfgObj.PSObject.Properties['relay_api_key']) { $cfgObj.relay_api_key = "" }
        if ($cfgObj.PSObject.Properties['api_key']) { $cfgObj.api_key = "" }
        $sanitizedCfgJson = ($cfgObj | ConvertTo-Json -Compress)
    } catch {
        $sanitizedCfgJson = "{}"
    }
}
[void]$sb.AppendLine("window.APP_CONFIG = " + $sanitizedCfgJson + ";")

[System.IO.File]::WriteAllText($outputFile, $sb.ToString(), [System.Text.Encoding]::UTF8)

$docTruyenPath = Join-Path $webDir "Doc_Truyen.html"
$indexPath = Join-Path $webDir "index.html"
if (Test-Path $docTruyenPath) {
    $htmlContent = [System.IO.File]::ReadAllText($docTruyenPath, [System.Text.Encoding]::UTF8)
    $htmlContent = $htmlContent -replace 'src="chapters\.js(?:\?v=[^"]+)?"', 'src="chapters.js"'
    [System.IO.File]::WriteAllText($indexPath, $htmlContent, [System.Text.Encoding]::UTF8)
    [System.IO.File]::WriteAllText($docTruyenPath, $htmlContent, [System.Text.Encoding]::UTF8)
}

$buildMapPy = Join-Path $toolsDir "build_map_and_graph.py"
if (Test-Path $buildMapPy) {
    try {
        python $buildMapPy | Out-Null
    } catch {}
}

Write-Host "Da dong bo thanh cong $($novelDirs.Count) bo truyen vao web/chapters.js (Active: $($activeDir.Name))." -ForegroundColor Green
