window.GRAPH_DATA = {
  "Chu_Thuat_Su_Dung_Gia": {
    "novel_key": "Chu_Thuat_Su_Dung_Gia",
    "novel_title": "Chu Thuat Su Dung Gia",
    "nodes": [
      {
        "id": "Momokawa Kotarou",
        "label": "Momokawa Kotarou",
        "name_orig": "Momokawa Kotarou",
        "eid": "CHAR-001",
        "faction": "Nhân vật chính",
        "color": "#8b5cf6",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Souma Yuuto",
        "label": "Souma Yuuto",
        "name_orig": "Souma Yuuto",
        "eid": "CHAR-002",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Tendou Ryuuichi",
        "label": "Tendou Ryuuichi",
        "name_orig": "Tendou Ryuuichi",
        "eid": "CHAR-003",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Yamada Genki",
        "label": "Yamada Genki",
        "name_orig": "Yamada Genki",
        "eid": "CHAR-004",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Ueta Youhei",
        "label": "Ueta Youhei",
        "name_orig": "Ueta Youhei",
        "eid": "CHAR-005",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nakai Shouta",
        "label": "Nakai Shouta",
        "name_orig": "Nakai Shouta",
        "eid": "CHAR-006",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Shimokawa Junnosuke",
        "label": "Shimokawa Junnosuke",
        "name_orig": "Shimokawa Junnosuke",
        "eid": "CHAR-007",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nakajima Haruma",
        "label": "Nakajima Haruma",
        "name_orig": "Nakajima Haruma",
        "eid": "CHAR-008",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Hayama Ritsuki (Rerite)",
        "label": "Hayama Ritsuki (Rerite)",
        "name_orig": "Hayama Ritsuki (Rerite)",
        "eid": "CHAR-009",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Yokomichi Hajime",
        "label": "Yokomichi Hajime",
        "name_orig": "Yokomichi Hajime",
        "eid": "CHAR-010",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Azuma Shin'ichi",
        "label": "Azuma Shin'ichi",
        "name_orig": "Azuma Shin'ichi",
        "eid": "CHAR-011",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Yama-Jun",
        "label": "Yama-Jun",
        "name_orig": "Yama-Jun",
        "eid": "CHAR-012",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Ooyama Daisuke",
        "label": "Ooyama Daisuke",
        "name_orig": "Ooyama Daisuke",
        "eid": "CHAR-013",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Sugino Takashi",
        "label": "Sugino Takashi",
        "name_orig": "Sugino Takashi",
        "eid": "CHAR-014",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Sakurai Touya",
        "label": "Sakurai Touya",
        "name_orig": "Sakurai Touya",
        "eid": "CHAR-015",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Kousaka Hiroki",
        "label": "Kousaka Hiroki",
        "name_orig": "Kousaka Hiroki",
        "eid": "CHAR-016",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Saitou Masaru",
        "label": "Saitou Masaru",
        "name_orig": "Saitou Masaru",
        "eid": "CHAR-017",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Itou Seiji",
        "label": "Itou Seiji",
        "name_orig": "Itou Seiji",
        "eid": "CHAR-018",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Higuchi Kyouya",
        "label": "Higuchi Kyouya",
        "name_orig": "Higuchi Kyouya",
        "eid": "CHAR-019",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Hirano Kouhei",
        "label": "Hirano Kouhei",
        "name_orig": "Hirano Kouhei",
        "eid": "CHAR-020",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Takashima Yuudai",
        "label": "Takashima Yuudai",
        "name_orig": "Takashima Yuudai",
        "eid": "CHAR-021",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Satou Yuuya",
        "label": "Satou Yuuya",
        "name_orig": "Satou Yuuya",
        "eid": "CHAR-022",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Futaba Meiko (Mei-chan)",
        "label": "Futaba Meiko (Mei-chan)",
        "name_orig": "Futaba Meiko (Mei-chan)",
        "eid": "CHAR-023",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Kisaragi Ryouko",
        "label": "Kisaragi Ryouko",
        "name_orig": "Kisaragi Ryouko",
        "eid": "CHAR-024",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Souma Sakura",
        "label": "Souma Sakura",
        "name_orig": "Souma Sakura",
        "eid": "CHAR-025",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Takanashi Kotori",
        "label": "Takanashi Kotori",
        "name_orig": "Takanashi Kotori",
        "eid": "CHAR-026",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Kenzaki Asuna",
        "label": "Kenzaki Asuna",
        "name_orig": "Kenzaki Asuna",
        "eid": "CHAR-027",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Natsukawa Minami",
        "label": "Natsukawa Minami",
        "name_orig": "Natsukawa Minami",
        "eid": "CHAR-028",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Randou Kyouko",
        "label": "Randou Kyouko",
        "name_orig": "Randou Kyouko",
        "eid": "CHAR-029",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Himeno Airi",
        "label": "Himeno Airi",
        "name_orig": "Himeno Airi",
        "eid": "CHAR-030",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Yoshizaki Hiroe",
        "label": "Yoshizaki Hiroe",
        "name_orig": "Yoshizaki Hiroe",
        "eid": "CHAR-031",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nonomiya Jun'ai",
        "label": "Nonomiya Jun'ai",
        "name_orig": "Nonomiya Jun'ai",
        "eid": "CHAR-032",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Hinagiku Haya",
        "label": "Hinagiku Haya",
        "name_orig": "Hinagiku Haya",
        "eid": "CHAR-033",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Reina Adelheid Ayase",
        "label": "Reina Adelheid Ayase",
        "name_orig": "Reina Adelheid Ayase",
        "eid": "CHAR-034",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nagae Yukiko",
        "label": "Nagae Yukiko",
        "name_orig": "Nagae Yukiko",
        "eid": "CHAR-035",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Satou Aya",
        "label": "Satou Aya",
        "name_orig": "Satou Aya",
        "eid": "CHAR-036",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nishiyama Minoru",
        "label": "Nishiyama Minoru",
        "name_orig": "Nishiyama Minoru",
        "eid": "CHAR-037",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Iijima Mayumi",
        "label": "Iijima Mayumi",
        "name_orig": "Iijima Mayumi",
        "eid": "CHAR-038",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Kitaouji Rurika",
        "label": "Kitaouji Rurika",
        "name_orig": "Kitaouji Rurika",
        "eid": "CHAR-039",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Kizaki Akane",
        "label": "Kizaki Akane",
        "name_orig": "Kizaki Akane",
        "eid": "CHAR-040",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Shinohara Emi",
        "label": "Shinohara Emi",
        "name_orig": "Shinohara Emi",
        "eid": "CHAR-041",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      }
    ],
    "edges": [],
    "factions": [
      "Khác",
      "Nhân vật chính"
    ]
  },
  "Cô Bạn Thuở Nhỏ Khăng Khăng Bạn Đời Của Cậu Ấy Là Tôi ―― Hóa Ra Người Phát Điên Lại Chính Là Cô Ấy": {
    "novel_key": "Cô Bạn Thuở Nhỏ Khăng Khăng Bạn Đời Của Cậu Ấy Là Tôi ―― Hóa Ra Người Phát Điên Lại Chính Là Cô Ấy",
    "novel_title": "Cô Bạn Thuở Nhỏ Khăng Khăng Bạn Đời Của Cậu Ấy Là Tôi ―― Hóa Ra Người Phát Điên Lại Chính Là Cô Ấy",
    "nodes": [
      {
        "id": "Elena",
        "label": "Elena",
        "name_orig": "Elena",
        "eid": "CHAR-001",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Mireille",
        "label": "Mireille",
        "name_orig": "Mireille",
        "eid": "CHAR-002",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Hầu tước Langley",
        "label": "Hầu tước Langley",
        "name_orig": "Hầu tước Langley",
        "eid": "CHAR-003",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Hầu tước Valfen",
        "label": "Hầu tước Valfen",
        "name_orig": "Hầu tước Valfen",
        "eid": "CHAR-004",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Alfred",
        "label": "Alfred",
        "name_orig": "Alfred",
        "eid": "CHAR-005",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Johann",
        "label": "Johann",
        "name_orig": "Johann",
        "eid": "CHAR-006",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Marie Lange",
        "label": "Marie Lange",
        "name_orig": "Marie Lange",
        "eid": "CHAR-007",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Dino",
        "label": "Dino",
        "name_orig": "Dino",
        "eid": "CHAR-008",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      }
    ],
    "edges": [],
    "factions": [
      "Khác"
    ]
  },
  "Tôi Đáng Lẽ Chỉ Là Một Ác Nữ Phản Diện Thông Thường Mà": {
    "novel_key": "Tôi Đáng Lẽ Chỉ Là Một Ác Nữ Phản Diện Thông Thường Mà",
    "novel_title": "Tôi Đáng Lẽ Chỉ Là Một Ác Nữ Phản Diện Thông Thường Mà",
    "nodes": [
      {
        "id": "Aurelia Rosenberg",
        "label": "Aurelia Rosenberg",
        "name_orig": "Aurelia Rosenberg",
        "eid": "CHAR-001",
        "faction": "Nhân vật chính",
        "color": "#8b5cf6",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Silphy Lumière",
        "label": "Silphy Lumière",
        "name_orig": "Silphy Lumière",
        "eid": "CHAR-002",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Felix",
        "label": "Felix",
        "name_orig": "Felix",
        "eid": "CHAR-003",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Dylan Cromwell",
        "label": "Dylan Cromwell",
        "name_orig": "Dylan Cromwell",
        "eid": "CHAR-004",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Nina",
        "label": "Nina",
        "name_orig": "Nina",
        "eid": "CHAR-005",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Theodore Wester",
        "label": "Theodore Wester",
        "name_orig": "Theodore Wester",
        "eid": "CHAR-006",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Elsa Eisenberg",
        "label": "Elsa Eisenberg",
        "name_orig": "Elsa Eisenberg",
        "eid": "CHAR-007",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Marta",
        "label": "Marta",
        "name_orig": "Marta",
        "eid": "CHAR-008",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Cedric Grandier",
        "label": "Cedric Grandier",
        "name_orig": "Cedric Grandier",
        "eid": "CHAR-009",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Maria",
        "label": "Maria",
        "name_orig": "Maria",
        "eid": "CHAR-010",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Beatrice",
        "label": "Beatrice",
        "name_orig": "Beatrice",
        "eid": "CHAR-011",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Gazelle",
        "label": "Gazelle",
        "name_orig": "Gazelle",
        "eid": "CHAR-012",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      },
      {
        "id": "Camila",
        "label": "Camila",
        "name_orig": "Camila",
        "eid": "CHAR-013",
        "faction": "Khác",
        "color": "#94a3b8",
        "role": "Nhân vật",
        "description": "",
        "skills": [],
        "timeline": []
      }
    ],
    "edges": [],
    "factions": [
      "Khác",
      "Nhân vật chính"
    ]
  }
};
